project:
  type: website
  resources:
    - "files/"

website:
  description: "Fatih Boyar's first blog"
  site-url: https://fatih-boyar.github.io/prob-lab 
  title: "Probability Lab"
  navbar:
    right:
      - about.qmd
      - href: license.qmd
        text: License

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

